5esheets/static/css/regular.css, 5esheets/static/css/style.css, 5esheets/static/js/index.js, 5esheets/templates/character.html, 5esheets/templates/sheet.html
We leverage https://github.com/markedjs/marked to render the markdown textarea content. The content is split between a textarea (markdown) and a div (rendered). By default, we hide the textearea and only show the rendered text. When we click on the div, we toggle the visibility of both elements, and once again when we leave focus.
Fixes #5
=> Allow the live rendering of the markdown content of textareas

5esheets/static/js/index.js
We only perform the carac macro replacement (eg `@int_mod` -> 4) on the markdown text, before rendrering it to HTML. This way, the replacement isn't persisted in DB.
Fixes #17
=> Don't persist the score value of caract modifer macros

Makefile, dnd5esheets/api.py, dnd5esheets/client/openapi.json, dnd5esheets/client/package-lock.json, dnd5esheets/client/package.json, dnd5esheets/client/src/5esheet-client/core/ApiError.ts, dnd5esheets/client/src/5esheet-client/core/ApiRequestOptions.ts, dnd5esheets/client/src/5esheet-client/core/ApiResult.ts, dnd5esheets/client/src/5esheet-client/core/CancelablePromise.ts, dnd5esheets/client/src/5esheet-client/core/OpenAPI.ts, dnd5esheets/client/src/5esheet-client/core/request.ts, dnd5esheets/client/src/5esheet-client/index.ts, dnd5esheets/client/src/5esheet-client/models/CharacterSchema.ts, dnd5esheets/client/src/5esheet-client/models/HTTPValidationError.ts, dnd5esheets/client/src/5esheet-client/models/ListCharacterSchema.ts, dnd5esheets/client/src/5esheet-client/models/PartySchema.ts, dnd5esheets/client/src/5esheet-client/models/PlayerSchema.ts, dnd5esheets/client/src/5esheet-client/models/UpdateCharacterSchema.ts, dnd5esheets/client/src/5esheet-client/models/ValidationError.ts, dnd5esheets/client/src/5esheet-client/services/CharacterService.ts, dnd5esheets/client/src/5esheet-client/services/DefaultService.ts, dnd5esheets/client/src/App.svelte, scripts/preprocess_openapi_json.py
We followed https://fastapi.tiangolo.com/advanced/generate-clients/#fastapi-app-with-tags to generate the 5ehseets API Typescript client, with types, interfaces and services.
The `make svelte-api-generate-api-client` target automatically fetches the `openapi.json` spec from the app itself, and [preprocesses](https://fastapi.tiangolo.com/advanced/generate-clients/#preprocess-the-openapi-specification-for-the-client-generator) to make sure we get consise method names. It then generates the typescript client code through `openapi-typescript-codegen`.
Autocompletion on method and arguments works like a charm:
Fixes #40
=> Generate the 5esheets typescript API client from the API spec

dnd5esheets/config/__init__.py, dnd5esheets/config/base.py, dnd5esheets/config/dev.py, dnd5esheets/config/prod.py
The prod configuration relies on a `.env` file that will need to be populated
with the app secret key.
Fixes #63
=> Introduce dev/prod configuration

dnd5esheets/api/character.py, dnd5esheets/api/login.py, dnd5esheets/api/party.py, dnd5esheets/api/player.py, dnd5esheets/config/__init__.py, dnd5esheets/config/base.py, dnd5esheets/config/prod.py, dnd5esheets/db/fixtures/dev.json, dnd5esheets/front/openapi.json, dnd5esheets/front/src/5esheets-client/services/PartyService.ts, dnd5esheets/repositories/base.py, dnd5esheets/repositories/character.py, dnd5esheets/repositories/party.py, dnd5esheets/repositories/player.py, dnd5esheets/schemas.py, dnd5esheets/security/user.py
This will make sure we scope the returned resources to those associated with the owner of the JWT.
```console
~/c/5esheets/d/front main !5 ?1 ❯ curl -s -X 'POST' \
'http://127.0.0.1:8000/api/login/token' \
-H 'accept: application/json' \
-H 'Content-Type: application/x-www-form-urlencoded' \
-d 'username=br%40test.com&password=azerty' | jq .
{
"access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJickB0ZXN0LmNvbSIsImV4cCI6MTY4NzY0NDM3M30.gIBqd8ZloatxcpADfuf3UsQVWyQh74_OvcC1GYwyAmc",
"token_type": "bearer"
}
~/c/5esheets/d/front main !5 ?1 ❯ curl -s -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJickB0ZXN0LmNvbSIsImV4cCI6MTY4NzY0NDM3M30.gIBqd8ZloatxcpADfuf3UsQVWyQh74_OvcC1GYwyAmc" http://localhost:8000/api/character/ | jq .
[
{
"id": 1,
"name": "Douglas …
```
=> Introduce a way to scope resources to the owner of the provided JWT

dnd5esheets/front/src/components/CharacterSheet.tsx, dnd5esheets/front/src/store/index.ts
Everytime the character level changes, we recompute the proficiency bonus, which in turn, recomputes the skill modifiers.
| Before | After |
| -- | -- |
|<img width="377" alt="Screenshot 2023-06-26 at 17 26 41" src="https://github.com/brouberol/5esheets/assets/480131/e1388ec3-3079-4c0e-98d9-d89057177b8a"> | <img width="381" alt="Screenshot 2023-06-26 at 17 26 46" src="https://github.com/brouberol/5esheets/assets/480131/64974df1-a5f3-4278-94ec-94de3afe2f23">|
=> Recompute the proficiency bonus from the character level

dnd5esheets/front/src/components/CharacterSheet.tsx, dnd5esheets/front/src/store/index.ts
The passive perception depends on:
- the level of mastery of the perception skill (none, proficient, master)
- the proficiency bonus
- the wisdom modifier
| Initial state | Increase WIS |Increase level | Increase perception mastery|
| -- | -- | -- | --|
|<img width="326" alt="Screenshot 2023-06-26 at 17 45 20" src="https://github.com/brouberol/5esheets/assets/480131/7edeb990-239c-45f3-b2ef-4064e625b34e">|<img width="324" alt="Screenshot 2023-06-26 at 17 42 32" src="https://github.com/brouberol/5esheets/assets/480131/ff81a103-a2b3-49c8-9706-3943411a697b"> | <img width="340" alt="Screenshot 2023-06-26 at 17 42 52" src="https://github.com/brouberol/5esheets/assets/480131/002a4338-3d52-4db8-bacc-307f08a08272">|<img width="342" alt="Screenshot 2023-06-26 at 17 43 02" …
=> Recompute the passive perception when the wisdom score or proficiency bonus change

Makefile, dnd5esheets/data/items-base.json, scripts/preprocess_base_item_json.py
We import and pre-process the SRD basic equipment list from 5e.tools. The data is massaged into a format that is more workable for us.
We generate an effect for the armors using the projected effect format that we're currently discussing in #77 (subject to change).
The generation of this dataset is added to the `run` make target dependency list.
This is part of #76
=> Import and pre-process the SRD basic equipment/items list

Makefile, dnd5esheets/data/items-base.json, dnd5esheets/data/translations-items-fr.json, poetry.lock, pyproject.toml, scripts/preprocess_base_item_json.py
I tried a very naive approach: either we have an exact match, or we don't import the translation. No levenshtein.
We only have 4 non matches:
```console
~/code/5esheets main *3 !7 ?1 ❯ make data
[+] Fetching base equipment data
No translation found for Arrows (20)
No translation found for Blowgun Needles (50)
No translation found for Crossbow Bolts (20)
No translation found for Sling Bullets (20)
```
Fixes #87
=> Fetch item translations from the `foundryvtt-dnd5e-lang-fr-fr` module data 

Makefile, dnd5esheets/app.py, dnd5esheets/config/base.py, dnd5esheets/config/prod.py, dnd5esheets/front/src/5esheets-client/core/OpenAPI.ts
Setup CORS in development mode only, as we have both a backend and frontend servers, running on different "domains":
- the backend runs on `localhost:8000`
- the frontend runs on `localhost:3000`
However, in prod, the frontend will only be static compiled files served by a CDN, and they will only hit the local domain.
To that end, we configure the `BASE` API host in the `OpenAPI.ts` configuration file according to the `NODE_ENV` we're running in. We do this via some make/sed magic, but it might be easier to simply keep a modified copy of `OpenAPI.ts` and simply `cp` it after a new client generation.
=> Setup CORS to allow API calls to come from the dev frontend server

.github/workflows/update-requirements-after-dependabot.yml
When Dependabot updates the python dependencies, this workflow will make sure to also update `requirements.txt` with it. This will save me about 5 minutes a week. Yay!
=> Trigger a workflow to update requirements.txt when dependabot creates a PR

Makefile, dnd5esheets/__init__.py, dnd5esheets/api/__init__.py, dnd5esheets/api/root.py, dnd5esheets/app.py, dnd5esheets/exceptions.py, dnd5esheets/middleware.py, dnd5esheets/spa.py, dnd5esheets/tests/conftest.py, scripts/start-app.sh
This removes any import-time side effects, and gets us closer from the Flask good practices that I'm trying to follow even with FastAPI.
=> Create the app via the app factory pattern

dnd5esheets/data/spells.json, dnd5esheets/front/openapi.json, dnd5esheets/front/src/5esheets-client/models/SpellCastingMaterial.ts, dnd5esheets/front/src/5esheets-client/models/SpellData.ts, dnd5esheets/front/src/5esheets-client/models/SpellRange.ts, dnd5esheets/schemas.py, dnd5esheets/tests/test_api_spell.py, scripts/preprocess_spells_json.py
This allowed me to unearth discrepancies between specific spells and our `SpellData` schema, and will make sure that each new spell we add to DB conforms with it.
=> Validate the schema of each spell in DB in unit tests

.gitignore, Makefile, dnd5esheets/config/base.py, dnd5esheets/middlewares.py, poetry.lock, pyproject.toml
To profile a given route, we run the server with profiling enabled (`make run-with-profiling`), and hit the same endpoint multiple times 
```python
>>> import timeit
>>> import httpx 
>>> timeit.timeit('httpx.get("http://localhost:8000/api/character/douglas-mctrickfoot")', globals={'httpx': httpx}, number=300)
```
We then shutdown the app, and run `make profile`, which generates this kind of profiling output
=> Allow the server to run with a profiling middleware, to measure spent time in request handling

dnd5esheets/admin/admin.py, dnd5esheets/app.py, dnd5esheets/cli.py, dnd5esheets/exceptions.py, dnd5esheets/models.py, poetry.lock, pyproject.toml
We launch 300 consecutive `get_character` request, and we observe that ~6% of the whole runtime is spent by deserializing JSON payloads from database (in `models.Json.process_result_value`).
By replacing the stdblib `json` module by [`orjson`](https://github.com/ijl/orjson) (written in rust), we speed up this deserialization step by a 2x factor.
I thus replaced all uses of `json` by `orjson` and made `ORJSONReponse` the default `FastAPI` response class.
=> Replace the stdlib json module by orjson

dnd5esheets/models.py
It's much lighter to compute than the hash of the whole model dict to JSON representation.
Calling `GET /api/spell/30` 300 times leads to the following profile.
The new etag computation makes the `handle_model_etag` span completely disappear from the profile.
=> By default, a model's etag is the sha1 of its last update datetime

dnd5esheets/app.py, dnd5esheets/config/base.py, dnd5esheets/config/prod.py
This implements best practice 9 from https://github.com/zhanymkanov/fastapi-best-practices#9-docs
=> Hide openapi/docs/redoc pages in production

dnd5esheets/app.py, dnd5esheets/config/base.py, dnd5esheets/config/prod.py, dnd5esheets/logs.py, poetry.lock, pyproject.toml
We allow two main logging strategies:
- logging to the console in a human-readable format
- logging to the console in a machine-readable format (JSON)
We accomplish this using `structlog` and a bit of `logging` elbow grease.
Several development-focused features can be leveraged:
- the `LOG_DEBUG` environment variable can be passed with a value of `true` or `1` to print the configuration of all loggers (app and libraries)
- the `SQLALCHEMY_ECHO` environment variable can be passed with a value of  `true` or `1` to print all SQL requests being sent out to the DB (this pre-existed this PR)
- the `LOG_FORMAT` environment variable can be passed with a value of `json` to have the logs be printed as JSON
To prettify the logs via `jq`, we can use
```
LOG_FORMAT=json make run 2>&1 | grep '{' …
```
=> Implement a solid logging strategy

dnd5esheets/logs.py, dnd5esheets/middlewares.py
This works due to the fact that `CorrelationIdMiddleware` sets a context variable (unique per asynchronous task, cf https://peps.python.org/pep-0567/). We can then fetch its value from the logging processors, and inject it into the event dict.
Example of 2 logs emitted during the same request:
```
2023-08-07 14:54:16.015774 [info     ] Computing etag                         [dnd5esheets.api.character] correlation_id=fb24d107db474ab0ae2be8eb6ad68231 filename=character.py func_name=handle_character_etag lineno=30 module=character pathname=/Users/br/code/5esheets/dnd5esheets/api/character.py
2023-08-07 14:54:16.035390 [info     ] GET /api/character/douglas-mctrickfoot [dnd5esheets.middlewares] correlation_id=fb24d107db474ab0ae2be8eb6ad68231 filename=middlewares.py func_name=dispatch …
```
=> Inject a unique correlation ID in each log emitted during a request's lifespan

dnd5esheets/front/src/store/index.ts
We see the Spell DC / Spell Attack Bonus values change when Douglas' spellcasting ability (INT) changes.
| INT=18 | INT=13 |
| -- | -- |
|<img width="328" alt="Screenshot 2023-08-09 at 11 16 03" src="https://github.com/brouberol/5esheets/assets/480131/41a34176-9377-493e-a3f5-e07aa2191cd5"> |<img width="335" alt="Screenshot 2023-08-09 at 11 16 09" src="https://github.com/brouberol/5esheets/assets/480131/aaecd40c-1318-41e3-9a2c-96920783bf56"> |
=> Express the spell dc effect calculation with the spell attack bonus value

dnd5esheets/api/item.py, dnd5esheets/front/openapi.json, dnd5esheets/front/src/5esheets-client/index.ts, dnd5esheets/front/src/5esheets-client/models/SearchResult.ts, dnd5esheets/front/src/5esheets-client/services/ItemService.ts, dnd5esheets/migrations/versions/623e8558c9ba_add_item_full_text_search_table.py, dnd5esheets/repositories/base.py, dnd5esheets/repositories/item.py, dnd5esheets/schemas.py, dnd5esheets/tests/conftest.py, dnd5esheets/tests/test_api_item.py, dnd5esheets/tests/test_repository_item.py
The way this works is by defining an SQLite search index table and relying on triggers to keep the search index in sync with the actual `item` table.
Every time an `Item` is inserted to, deleted from, or updated in the `item` table, a trigger is executed to mirror the changes into the `item_search_index` virtual table.
This way, the search index is always up-to-date.
We also introduce a way to favor result of a given language, to make sure to surface the results in the player's locale/language first.
=> Implement a full text search service for Items using SQLite fts5

dnd5esheets/front/src/components/CharacterSheet.tsx
Once the `NaN` appears in the label, we can't delete it and can't overwrite it.
https://github.com/brouberol/5esheets/assets/480131/61777629-217c-4e44-81e7-a39c7d442dad 
https://github.com/brouberol/5esheets/assets/480131/29fb2b6c-7622-44e5-a448-a5b464855b4d
=> Fix: if the whole ability score is deleted, don't insert NaN in the label

.github/labeler.yml, dnd5esheets/admin/admin.py, dnd5esheets/api/character.py, dnd5esheets/api/party.py, dnd5esheets/api/player.py, dnd5esheets/cli.py, dnd5esheets/db/fixtures/dev.json, dnd5esheets/exceptions.py, dnd5esheets/front/openapi.json, dnd5esheets/front/src/5esheets-client/services/PartyService.ts, dnd5esheets/repositories/character.py, dnd5esheets/repositories/equipped_item.py, dnd5esheets/repositories/known_spell.py, dnd5esheets/repositories/party.py, dnd5esheets/repositories/player.py, dnd5esheets/security/policies.py, dnd5esheets/security/policies/base.py, dnd5esheets/security/policies/character.py, dnd5esheets/security/policies/party.py, dnd5esheets/security/policies/player.py, dnd5esheets/tests/conftest.py, dnd5esheets/tests/test_api_character.py, dnd5esheets/tests/test_api_party.py, dnd5esheets/tests/test_api_player.py, dnd5esheets/tests/test_repository_character.py, dnd5esheets/tests/test_repository_equipped_item.py, dnd5esheets/tests/test_repository_party.py, dnd5esheets/tests/utils.py
This PR introduces security policies that we hook onto API routes via [path operation decorator dependencies](https://fastapi.tiangolo.com/tutorial/dependencies/dependencies-in-path-operation-decorators/).
This allows to gate the access to the resource by:
- checking that the player is logged in
- checking that the _role_ of the player allows them to access the resource (whether they are the owner, a party member or the party DM) 
Fixes #225
=> Protect API resources with security policies when multitenancy is enabled

dnd5esheets/migrations/versions/2023_08_09_15_45_623e8558c9ba_add_item_full_text_search_table.py, dnd5esheets/migrations/versions/2023_08_10_14_15_e3f5418ab972_add_spell_full_text_search_table.py
Now that the sqlite3 version has been pinned, we can now leverage more modern features, such as the `->>` [operator](https://www.sqlite.org/json1.html#jptr)
=> Improve migration readability by replacing json_extract by ->> operator

Dockerfile, scripts/compile-libsqlite-linux.sh, scripts/start-app.sh
We compile `libsqlite3.so` as part of the `docker build` process, in a build step,
copy it into the final image, and hook it into the app via `LD_PRELOAD`.
```console
% make docker-run
...
2023-08-24 11:20:13.685774 [info     ] Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
```
```console
% curl localhost:8000/api/debug/sqlite-version
{"version":"3.42.0"}
```
=> Pin the sqlite version when running the app in docker

dnd5esheets/front/package-lock.json, dnd5esheets/front/package.json, dnd5esheets/front/src/App.tsx, dnd5esheets/front/src/components/CharacterSheet.tsx, dnd5esheets/front/src/components/MarkdownRenderedEditableBox.tsx
This is imperfect but works as-is. 
| Before | Markdown edition | Rendered |
| -- | -- | -- |
| <img width="301" alt="Screenshot 2023-10-30 at 15 41 06" src="https://github.com/brouberol/5esheets/assets/480131/4af4d50b-af3e-4f95-88f8-c903bc0cdb29">|<img width="336" alt="Screenshot 2023-10-30 at 15 41 20" src="https://github.com/brouberol/5esheets/assets/480131/e6052abc-5f5f-48af-bee6-7932adea62a5"> |<img width="306" alt="Screenshot 2023-10-30 at 15 41 24" src="https://github.com/brouberol/5esheets/assets/480131/cfc30dea-9ddc-43e5-8302-64348c41ef28">|
⚠️ The layout jumps all over the place when we add long text. To be fixed in another PR.
=> Add markdown rendering to free-form editable text boxes

dnd5esheets/front/src/components/icons/icon.tsx, dnd5esheets/front/src/components/icons/minus.tsx, dnd5esheets/front/src/components/icons/plus.tsx, dnd5esheets/front/src/components/number-input/index.tsx
Not sure why, but storybook fails to load the lucide icons from the package, so this PR copies the two we use directly in the src/components.
=> Import lucide icons directly
