brouberol/5esheets

- 5esheets/app.py
- Dockerfile
> Define a dockerfile to ease running the app

- 5esheets/static/js/index.js
| French | English |
| -- | -- |
|<img width="243" alt="Screenshot 2023-06-14 at 11 47 18" src="https://github.com/brouberol/5esheets/assets/480131/ccff19a5-3663-4451-b962-11d01c474247"> | <img width="243" alt="Screenshot 2023-06-14 at 11 47 01" src="https://github.com/brouberol/5esheets/assets/480131/9453f549-33c5-4a28-a9fb-13c374c02a08"> |
Fixes #10
> Sort the skills according to the translated text

- 5esheets/static/css/components.css
- 5esheets/static/css/regular.css
- 5esheets/static/css/vars.css
- 5esheets/templates/character.html
- 5esheets/templates/sheet.html
I removed most of the long CSS positional selectors, introduced variables and components.
It should be easier to maintain.
Fixes #6 (for now)
> CSS Cleanup

- 5esheets/static/css/components.css
- 5esheets/static/css/regular.css
- 5esheets/static/css/vars.css
| Light | Dark |
| -- | -- |
| <img width="1172" alt="Screenshot 2023-06-19 at 22 41 46" src="https://github.com/brouberol/5esheets/assets/480131/31ea4a76-d351-4cd7-8cd9-700dcd5863df">|<img width="1156" alt="Screenshot 2023-06-19 at 22 41 37" src="https://github.com/brouberol/5esheets/assets/480131/a0713d8b-1494-45ef-98be-6ed40b64a058"> |
> Implement a light/dark theme

- 5esheets/app.py
- 5esheets/db.py
- 5esheets/migrations/20230614145526_first_migration.py
- 5esheets/models.py
- 5esheets/templates/characters.html
- poetry.lock
- pyproject.toml
- requirements.txt
We rely on [Peewee](https://docs.peewee-orm.com/en/latest/index.html) as it it simpler than SQLAlchemy, and yet powerful enough for this application.
> Use a simple ORM instead of handcrafted SQL queries

- 5esheets/static/css/components.css
- 5esheets/static/css/vars.css
- 5esheets/static/js/index.js
- 5esheets/templates/character.html
- 5esheets/templates/spells.html
**Skill score**
**Spell attack bonus**
**Spell DC**
**Passive perception**
> Display a tooltip explaining the skill, passive perception, spell DC and spell attack bonus scores

- 5esheets/app.py
- 5esheets/commands.py
- 5esheets/db.py
- 5esheets/models.py
- poetry.lock
- pyproject.toml
> Replace Peewee by SQLAlchemy, to support asynchronous queries in the future

- Makefile
- dnd5esheets/app.py
- dnd5esheets/db.py
- dnd5esheets/repositories.py
- dnd5esheets/schemas.py
- poetry.lock
- pyproject.toml
- requirements.txt
Fixes #42
We also fixed some typing violations
> Configure mypy, ruff and black as local checkers

- Dockerfile
- scripts/start-app.sh
> Apply alembic migrations at startup before exec-ing uvicorn

- .github/dependabot.yml
> Setup dependabot to regularly upgrade python & js dependencies

- dnd5esheets/front/package.json
- dnd5esheets/front/src/5esheets-client/core/request.ts
Remove axios and undici to use fetch instead.
> remove axios and undici to use fetch instead

- dnd5esheets/front/src/store/index.ts
- Automatically recompute the initiative score
- Automatically recompute the spell DC score
- Automatically recompute the spell attack bonus score
> Add computation effects for initiative, spell DC and spell attack bonus

- .github/workflows/testing-backend.yml
- .github/workflows/testing-frontend.yml
- .github/workflows/testing.yml
- Makefile
- dnd5esheets/front/package.json
- dnd5esheets/front/src/store/index.ts
We run `prettier -c` which checks whether the files are correctly formatted, when `prettier -w` automatically reformats the files. The latter will exit with status `0` even if some files were incorrectly formatted.
> Run prettier in CI

- dnd5esheets/config/test.py
- dnd5esheets/schemas.py
- dnd5esheets/tests/test_api_character.py
- dnd5esheets/tests/test_api_login.py
- dnd5esheets/tests/test_api_party.py
- dnd5esheets/tests/test_api_player.py
- dnd5esheets/tests/utils.py
- We need a secret key in test as well
- Add unit tests for API handlers
Fixes #80
> Add unit tests for the API handlers

- .github/workflows/testing-backend.yml
- .github/workflows/testing-frontend.yml
- Makefile
Fixes #94 
Fixes #95
Closes #96
> Run the frontend unit tests in CI

- dnd5esheets/front/src/components/CharacterList.tsx
- dnd5esheets/front/src/routes/index.tsx
Instead of relying on the store fake local data, we hit the backend API to list characters
> List characters by hitting the /api/character/ API

- dnd5esheets/db.py
- dnd5esheets/repositories/character.py
- dnd5esheets/repositories/party.py
- dnd5esheets/tests/conftest.py
- dnd5esheets/tests/test_model.py
- dnd5esheets/tests/test_repository_character.py
- dnd5esheets/tests/test_repository_party.py
- dnd5esheets/tests/test_repository_player.py
- poetry.lock
- pyproject.toml
This PR adds tests for the `player`, `character` and `party` repositories.
> Add tests for all repositories

- dnd5esheets/api/character.py
- dnd5esheets/repositories/character.py
- dnd5esheets/tests/test_api_character.py
- dnd5esheets/tests/test_model.py
- dnd5esheets/tests/test_repository_character.py
- Implement the character deletion API
- Don't crash when attempting to compute the ETag of a missing resource
> Implement the Character deletion API

- dnd5esheets/admin.py
- dnd5esheets/app.py
- dnd5esheets/models.py
- poetry.lock
- pyproject.toml
- requirements.txt
This allows us to list, view, edit, create and delete DB models in a web interface, under `/admin`
> Define an admin interface for DB models using sqlmodel

- Makefile
- dnd5esheets/admin/__init__.py
- dnd5esheets/admin/admin.mk
- dnd5esheets/admin/admin.py
- dnd5esheets/admin/statics/pygments.css
- dnd5esheets/admin/templates/details_custom.html
- poetry.lock
- pyproject.toml
Make it easier to read large JSON data fields by rendering them with syntax highlighting.
| Before | After |
| -- | -- |
|<img width="100%" alt="Screenshot 2023-08-03 at 14 59 32" src="https://github.com/brouberol/5esheets/assets/480131/e67d36db-3451-466a-a914-e576461ac8a3"> |<img width="100%" alt="Screenshot 2023-08-03 at 14 59 45" src="https://github.com/brouberol/5esheets/assets/480131/692501d6-8ecb-4056-ba77-5200393f330e"> |
> [admin] Pretty print and colorize JSON fields in models

- dnd5esheets/api/character.py
- dnd5esheets/front/openapi.json
- dnd5esheets/front/src/5esheets-client/models/EquippedItemSchema.ts
- dnd5esheets/front/src/5esheets-client/services/CharacterService.ts
- dnd5esheets/repositories/character.py
- dnd5esheets/repositories/equipped_item.py
- dnd5esheets/schemas.py
- dnd5esheets/tests/test_api_character.py
- dnd5esheets/tests/test_repository_character.py
- dnd5esheets/tests/test_repository_equipped_item.py
These will be useful for when a player wants to change the currently equipped weapon, for example, or change armor.
> Add APIs to equip and unequip an item for a given character

- dnd5esheets/api/character.py
- dnd5esheets/front/openapi.json
- dnd5esheets/front/src/5esheets-client/models/RestrictedKnownSpellSchema.ts
- dnd5esheets/front/src/5esheets-client/services/CharacterService.ts
- dnd5esheets/repositories/character.py
- dnd5esheets/repositories/known_spell.py
- dnd5esheets/schemas.py
- dnd5esheets/tests/conftest.py
- dnd5esheets/tests/test_api_character.py
- dnd5esheets/tests/test_repository_character.py
This will be useful when we implement the spellbook part of the character sheet.
> Add APIs to prepare and unprepare a spell for a given character

- dnd5esheets/api/item.py
- dnd5esheets/api/root.py
- dnd5esheets/front/openapi.json
- dnd5esheets/front/src/5esheets-client/index.ts
- dnd5esheets/front/src/5esheets-client/services/ItemService.ts
- dnd5esheets/repositories/item.py
- dnd5esheets/tests/test_api_item.py
- dnd5esheets/tests/test_repository_item.py
```python
~/code/5esheets main !4 ?4 ❯ curl localhost:8000/api/item/1 | jq .
{
"name": "Arrow",
"data": {
"meta": {
"translations": {
"fr": {
"name": "Flèche",
"description": "Munitions standard utilisées pour les arcs de toutes sortes. Ces flèches banales sont fabriquées à partir d'un manche en bois lisse, avec des plumes d'oie et un revêtement en métal martelé."
}
},
"rarity": "none",
"weight": 0.05,
"value": 5
},
"source": {
"book": "PHB",
"page": 150
},
"srd": true,
"subtype": "A",
"type": "munition"
}
}
```
> Add an API to display an item

- dnd5esheets/api/spell.py
- dnd5esheets/migrations/versions/e3f5418ab972_add_spell_full_text_search_table.py
- dnd5esheets/repositories/spell.py
- dnd5esheets/tests/test_api_spell.py
- dnd5esheets/tests/test_repository_item.py
- dnd5esheets/tests/test_repository_spell.py
Exactly similar to #207, but for spells.
Fixes #205
> Implement the spell search API

- .github/workflows/testing-backend.yml
Run tests on both python 3.11 and 3.12
> Run tests on both python3.11 and python3.12

- dnd5esheets/config/base.py
- dnd5esheets/config/prod.py
- dnd5esheets/middlewares.py
We were hitting CORS issues when running the app in http://localhost:3000
> Allow the dev app to run in both 127.0.0.1/localhost:3000

- dnd5esheets/db/fixtures/dev.json
- dnd5esheets/front/openapi.json
- dnd5esheets/front/src/5esheets-client/models/CharacterSheet.ts
- dnd5esheets/schemas.py
> Add exhaustion level to the main character data schema

- .github/workflows/docs.yml
- .github/workflows/lint-gh-actions.yml
> Lint github actions using actionlint
